version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "07:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 20
    reviewers:
      - "chauss"
