dbContainerName  = "recipy-backend-postgres-db"
dbName           = "recipy-backend"
dbSuperUser      = "root"
dbPassword       = "root"
appContainerName = "recipy-backend-application"
webContainerName = "recipy-website"