dbName                                   = "recipy-backend"
dbSuperUser                              = "root"
dbPassword                               = "root"
googleApplicationCredentialsFilePath     = "/tmp/google-application-credentials.json"
googleApplicationCredentialsFileHostPath = "/tmp/google-application-credentials.json"