variable "dbContainerName" {}
variable "dbName" {}
variable "dbSuperUser" {}
variable "dbPassword" {}
variable "appContainerName" {}
variable "webContainerName" {}
variable "imageDataPath" {}
variable "googleApplicationCredentialsFilePath" {}
variable "googleApplicationCredentialsFileHostPath" {}