package de.chauss.recipy.service

enum class ErrorCodes(val value: Int) {
    // Recipe
    CREATE_RECIPE_RECIPE_NAME_ALREADY_EXISTS(100),
    DELETE_RECIPE_RECIPE_ID_NOT_FOUND(120),
    DELETE_RECIPE_UNKNOWN_REASON(121),

    // Preparation Step
    CREATE_PREPARATION_STEP_RECIPE_ID_DOES_NOT_EXIST(130),
    UPDATE_PREPARATION_STEP_PREPARATION_STEP_ID_NOT_FOUND(135),
    DELETE_PREPARATION_STEP_PREPARATION_STEP_ID_NOT_FOUND(140),
    DELETE_PREPARATION_STEP_UNKNOWN_REASON(141),

    // Ingredient
    CREATE_INGREDIENT_INGREDIENT_NAME_ALREADY_EXISTS(200),
    DELETE_INGREDIENT_INGREDIENT_ID_NOT_FOUND(220),
    DELETE_INGREDIENT_UNKNOWN_REASON(221),
    DELETE_INGREDIENT_INGREDIENT_STILL_HAS_USAGES(222),

    // Ingredient Unit
    CREATE_INGREDIENT_UNIT_INGREDIENT_UNIT_NAME_ALREADY_EXISTS(300),
    DELETE_INGREDIENT_UNIT_UNKNOWN_REASON(320),
    DELETE_INGREDIENT_UNIT_INGREDIENT_UNIT_ID_NOT_FOUND(321),
    DELETE_INGREDIENT_UNIT_INGREDIENT_UNIT_STILL_HAS_USAGES(322),

    // Ingredient Usage
    CREATE_INGREDIENT_USAGE_INGREDIENT_ID_DOES_NOT_EXIST(400),
    CREATE_INGREDIENT_USAGE_INGREDIENT_UNIT_ID_DOES_NOT_EXIST(401),
    CREATE_INGREDIENT_USAGE_RECIPE_ID_DOES_NOT_EXIST(402),
    CREATE_INGREDIENT_USAGE_INGREDIENT_ALREADY_USED_IN_RECIPE(403),
    UPDATE_INGREDIENT_USAGE_INGREDIENT_USAGE_ID_NOT_FOUND(410),
    UPDATE_INGREDIENT_USAGE_INGREDIENT_ID_NOT_FOUND(411),
    UPDATE_INGREDIENT_USAGE_INGREDIENT_UNIT_ID_NOT_FOUND(412),
    UPDATE_INGREDIENT_USAGE_RECIPE_ID_NOT_FOUND(413),
    UPDATE_INGREDIENT_USAGE_INGREDIENT_ALREADY_USED_IN_RECIPE(414),
    DELETE_INGREDIENT_USAGE_INGREDIENT_USAGE_ID_NOT_FOUND(420),
    DELETE_INGREDIENT_USAGE_UNKNOWN_REASON(421),

    // Recipe Image
    ADD_RECIPE_IMAGE_RECIPE_DOES_NOT_EXIST(500),
    ADD_RECIPE_IMAGE_NO_IMAGE_UPLOADED(501),
    ADD_RECIPE_IMAGE_UNKNOWN_REASON(502),
    DELETE_RECIPE_IMAGE_IMAGE_DOES_NOT_EXIST(520);

    companion object {
        fun fromInt(value: Int) = values().firstOrNull { it.value == value }
    }
}