name: Build and test

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      #      - name: Setup Java
      #        uses: actions/setup-java@v2
      #        with:
      #          java-version: '17'
      #          distribution: 'temurin'

      #      - name: Build and test with Maven
      #        run: ./mvnw --batch-mode --update-snapshots verify

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login To DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build And Push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64/v8
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/recipy-backend:alpha-0.0.1

