name: Build and Test Dependabot Branches

on:
  push:
    branches:
      - dependabot/**
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test
        run: ./mvnw --update-snapshots --no-transfer-progress --errors clean verify

      - uses: scacap/action-surefire-report@v1
        with:
          report_paths: "**/surefire-reports/TEST-*.xml"
          check_name: Test Results
